services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=${BACKEND_PORT}
    container_name: persona-ai-backend-prod
    env_file:
      - .env.production         # Docker orchestration variables (ports, etc.)
      - ./backend/.env.production # Backend-specific variables
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT}
      # Database variables are loaded from backend/.env via env_file
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend/uploads:/app/uploads
    # Using default Docker network
    restart: unless-stopped
    # No database dependency since using external database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - BACKEND_PORT=${BACKEND_PORT}
    container_name: persona-ai-frontend-prod
    env_file:
      - .env.production         # Docker orchestration variables (ports, etc.)
    environment:
      - NODE_ENV=production
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    # Using default Docker network
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTEND_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# Volume mapping for persistent uploads storage
# Using default Docker bridge network