version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: persona-ai-backend-prod
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT}
      - DB_HOST=${EXTERNAL_DB_HOST}
      - DB_PORT=${EXTERNAL_DB_PORT}
      - DB_NAME=${EXTERNAL_DB_NAME}
      - DB_USER=${EXTERNAL_DB_USER}
      - DB_PASSWORD=${EXTERNAL_DB_PASSWORD}
      - DB_ENCRYPT=${EXTERNAL_DB_ENCRYPT}
      - DB_TRUST_CERT=${EXTERNAL_DB_TRUST_CERT}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - persona-network
    restart: unless-stopped
    # No database dependency since using external database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persona-ai-frontend-prod
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - persona-network
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# No volumes needed for external database setup

networks:
  persona-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16