version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: persona-ai-backend-dev
    environment:
      - NODE_ENV=development
      - PORT=${BACKEND_PORT}
      - DB_HOST=${EXTERNAL_DB_HOST}
      - DB_PORT=${EXTERNAL_DB_PORT}
      - DB_NAME=${EXTERNAL_DB_NAME}
      - DB_USER=${EXTERNAL_DB_USER}
      - DB_PASSWORD=${EXTERNAL_DB_PASSWORD}
      - DB_ENCRYPT=${EXTERNAL_DB_ENCRYPT}
      - DB_TRUST_CERT=${EXTERNAL_DB_TRUST_CERT}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "9229:9229"  # Node.js debugging port
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/uploads:/app/uploads
      - /app/node_modules
    networks:
      - persona-network-dev
    restart: unless-stopped
    # No database dependency since using external database
    command: npm run dev
    stdin_open: true
    tty: true

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: persona-ai-frontend-dev
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:${BACKEND_PORT}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    networks:
      - persona-network-dev
    restart: unless-stopped
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
    stdin_open: true
    tty: true

# No volumes needed for external database setup

networks:
  persona-network-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16